### PR TITLE
Create Package.swift

### PR DESCRIPTION
**Pull request by jiangri927**

### CODE REVIEW

**Comment by jiangri927** [comment]
@ezugaj . I made package.swift. Can we merge it to use at package manager of xcode?

**Comment by ezugaj** [comment]
Hi @jiangri927 thanks for your change. Please expect to have it merged next week, after validation.

**Comment by ezugaj** [comment]
Hi @jiangri927, I have created new PR https://github.com/voxeet/voxeet-uxkit-ios/pull/37 for SPM support. It turned out, that we need do slightly more to enable both SPM and non-SPM integration for UXKit. It is under review and internal testing. 

Cheers,
Edyta

**Comment by ezugaj** [comment]
Closing as the feature is already integrated.

**Pull request closed without merging**
